### ISSUE TITLE
NAV2 Doesn't Abort The NAV2 Goal

### ISSUE THREAD

**Issue by yigitboracagiran** [ros-navigation/navigation2#4432]
**Required Info:**
When I send the robot to an occupied cell with NAV2 goal on RVIZ2, I'm expecting to abort the NAV2 goal. But instead of abort, robot is going to an unoccupied cell which is close to real NAV2 goal which I sent. Can we abort the NAV2 goal in this situation?

- Operating System:
  Ubuntu 22.04
  
- ROS2 Version:
Humble

- Version or commit hash:
ros-humble-navigation2	1.1.15-1jammy.20240530.113754

- DDS implementation:
Eclipse Cyclone DDS

#### Steps to reproduce issue
1- Run a simulation of a robot
2- Open the navigation on RVIZ2
3- Send a NAV2 goal on RVIZ2 to on the obstacle (to occupied cell)

#### Expected behavior
4- Aborting the NAV2 goal.

#### Actual behavior
4- It won't abort the NAV2 goal, instead it will go to the an unoccupied cell which is close to the real NAV2 goal.
In the below video, I'm sending the robot to an obstacle with DWB.

https://github.com/ros-navigation/navigation2/assets/111417887/6891a652-ea7f-41f3-9e64-9e5ec3a815b5

**Comment by SteveMacenski** [comment]
All planners have some kind of `tolerance` parameter. Set that to zero if only exact solutions are valid. For example for NavFn https://github.com/ros-navigation/navigation2/blob/main/nav2_bringup/params/nav2_params.yaml#L281

That should just straight up reject because there's no path for the rest of the system to follow!
