### ISSUE TITLE
Make PipelineSequence and RoundRobinNode return Running

### ISSUE THREAD

**Issue by tonynajjar** [ros-navigation/navigation2#4782]
As done for the [RecoveryNode](https://github.com/ros-navigation/navigation2/pull/4777), the PipelineSequence and RoundRobinNode should be adapted to return RUNNING when a child returns a status non-terminal to the control node.

**Comment by SteveMacenski** [comment]
@tonynajjar can we consolidate this ticket and https://github.com/ros-navigation/navigation2/issues/4776 since they're both talking about the same thing: fixing or agreeing to the behavior on control flow nodes? I think we can fold https://github.com/ros-navigation/navigation2/issues/4776 into this ticket by including `RecoveryNode`.
